### ISSUE TITLE
[Feature Request] Cater for plantuml content in asciidoctor file

### ISSUE THREAD

**Issue by Skilly** [asciidoctor/asciidoctor-browser-extension#160]
Like many others, I too rely on this fantastic tool regularly, to preview my asciidoctor content as I'm developing it. 

My documents often contain plantuml content and it would be great if the diagrams appeared rendered correctly.

**Comment by mojavelinux** [comment]
I agree this would be a useful addition. I think that it should be done using a service. @Mogztter can correct me if I'm wrong, but a Chrome extension can't execute programs in other languages. So that would mean it needs to submit the diagram to a service and get back an image result. Of course, if we chose an open service, it's something that could be run on the location machine.

Something like: https://github.com/bitjourney/plantuml-service

Asciidoctor Diagram provides the infrastructure to bridge the custom block to a service like this, so it's something we'd have to collaborate on if we want to avoid reinventing what Asciidoctor Diagram does.

I'm open to other suggestions as well.

**Comment by Mogztter** [comment]
Viz.js looks promising but I don't really understand the correlation between PlantUML and Graphviz ? PlantUML is the language/format and Graphiz the rendering engine ?

> So that would mean it needs to submit the diagram to a service and get back an image result. Of course, if we chose an open service, it's something that could be run on the location machine.

Yes we could do that but I don't like to rely on a third-party service 😞
