### ISSUE TITLE
Don't show document title when noheader attribute is set

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-browser-extension#208]
When the noheader attribute is set, the document title should be hidden. The same is true if the notitle attribute is set. Currently, the only way to hide the document title is to unset the showtitle attribute.

Example:

```
= Document Title
:noheader:

The document title should be hidden.
```

**Comment by Mogztter** [comment]
So what needs to be done:

1. Remove `showtitle` from the default attributes: https://github.com/asciidoctor/asciidoctor-browser-extension/blob/f53773d879e0efb6759a6423b457c0d6e4213b35/app/js/renderer.js#L217
2. Load the document and check if the `noheader` or the `notitle` attribute is defined
    * @mojavelinux Is it allowed to use `!noheader` `noheader!` `!notitle` or `notitle!` ? I think we should check that `doc.getAttribute('noheader') === true || doc.getAttribute('notitle') === true` right ?
3. If the `noheader` or the `notitle` attribute is defined, convert the document
4. Otherwise, add `showtitle` and convert the document

.pseudo-code.js
```js
const hideDocumentTitle = (doc) => (doc.getAttribute('noheader') === true || doc.getAttribute('notitle') === true);

const options = buildAsciidoctorOptions(settings);
const doc = processor.load(source, options);
if (!hideDocumentTitle(doc)) {
  options.attributes.append(' showtitle');
}
return new AsciidoctorDocument(doc, doc.convert(options));
```

**Comment by mojavelinux** [comment]
> Is it allowed to use !noheader noheader! !notitle or notitle! ? I think we should check that doc.getAttribute('noheader') === true || doc.getAttribute('notitle') === true right ?

Actually, we should use isAttribute, not getAttribute.

That would be:

```js
doc.isAttribute('noheader') ||
  (!doc.isAttribute('showtitle') && doc.isAttribute('notitle'))
```

The check for showtitle is due to the fact that core isn't correctly merging the meaning of these two attributes.

That logic in English would be:

* If noheader is set, don't output the header
* If notitle is set, and showtitle is not set, don't output the title

If both showtitle and notitle are set, showtitle wins.
