### ISSUE TITLE
May cause GitLab web editor to refresh and lose uncommitted edits to adoc files

### ISSUE THREAD

**Issue by leif81** [asciidoctor/asciidoctor-browser-extension#225]
Initially reported here: https://twitter.com/leif81/status/978667106983206914

@mojavelinux said on Twitter: "It's getting confused by the file extension on the URL."

## Steps to reproduce

1. In Chrome install the Asciidoctor extension and have it enabled
2. Browse to an `.adoc` file in GitLab (e.g. https://gitlab.com/leif81/test/blob/master/README.adoc)
3. Click Edit
4. Make some changes to the file, but don't commit yet
5. Wait

## Actual results

The GitLab web editor page eventually refreshes and any uncommitted changes to the file will be lost.

## Expected results

The GitLab web editor to not refresh and lose changes.

## Workaround

Disable the Asciidoctor extension and revisit the GitLab page.

**Comment by leif81** [comment]
Possibly related to #129

**Comment by mojavelinux** [comment]
#129 would essentially be a workaround. It makes it possible to disable the refresh for remote files. But then you have to wonder why it is even interacting with a page that is not a candidate for preview. I think that's because it's seeing the .adoc extension and thinking it's supposed to operate on this page.

**Comment by Mogztter** [comment]
@leif81 Thanks for your report!
Though, I do not reproduce this issue 🤔
I can't test on your repository ("The page could not be found or you don't have permission to view it.") but I tried on the Antora repository and the extension does not refresh the page because the `Content-Type` is `text/html`:

https://github.com/asciidoctor/asciidoctor-browser-extension/blob/691930172d56e53b3a42ca68a22dcafeeae4c987/app/js/loader.js#L72-L74

https://github.com/asciidoctor/asciidoctor-browser-extension/blob/691930172d56e53b3a42ca68a22dcafeeae4c987/app/js/loader.js#L134-L137

More specifically I'm using this page: https://gitlab.com/antora/antora/edit/master/README.adoc

Are you using the latest version of the extension ?

@mojavelinux Do you reproduce this issue ?

**Comment by mojavelinux** [comment]
Well, I suppose I should actually check. I was speaking of past observations, but this could have been fixed since then. Testing...

**Comment by mojavelinux** [comment]
I was in the edit view for over a minute with pending changes and the tab did not refresh.

I'm using  1.5.5.112

**Comment by leif81** [comment]
@Mogztter It appears you have to be signed into GitLab to view a file, even in a public repo.

Yes I've had some issues reproducing it too. I first experience the issue last fall, but when I went to report it I couldn't reliably reproduce it so I abandoned the idea. Then I went back to editing "for-real" it'd happen and I'd lose my changes. About a month ago I tried disabling the extension, and since then it hasn't happened at all so I figured it might have been related to that.

**Comment by leif81** [comment]
I'm using 1.5.5.112 too. I can't say what version I would have been using a month or so ago before I had disabled the extension.

**Comment by mojavelinux** [comment]
Can you enable it again and let it run to see if it happens again. I know that sounds risky, but it would be for a good cause ;)

**Comment by leif81** [comment]
@mojavelinux Sure done, I'll report back.

**Comment by leif81** [comment]
Not quite the silver bullet yet, but I am seeing the random GitLab `.adoc` page refreshes with `1.5.5.112`. However, the times I've seen it happen I was not editing the page, just viewing it, so no harm was done.

**Comment by Mogztter** [comment]
Thanks for the follow-up.
Are you using Chrome ? I will try to reproduce the issue :)

**Comment by leif81** [comment]
Yes Chrome, with latest update. `Version 65.0.3325.181 (Official Build) (64-bit)`

**Comment by leif81** [comment]
Ok it happened for me just now.
The page refreshed when editing an `.adoc` in GitLab and I lost my uncommitted changes. I had the tab open for several minutes. At one point I walked away to get some food and came back and my edits were gone. :eyes:

**Comment by Mogztter** [comment]
Do you have a 🐈 ? 😅

**Comment by leif81** [comment]
Hah, no pets! Co-workers yes!

**Comment by mojavelinux** [comment]
I don't think this is the Asciidoctor browser extension that's doing this. I've noticed that there are certain situations when the GitLab UI refreshes when returning to or otherwise reactiving a tab. And I've heard people complain about this who are not using the Asciidoctor browser extension. That leads me to conclude that this is a bug in the GitLab UI. I'll admit, though, this is hard to track down.

**Comment by mojavelinux** [comment]
(To be honest, I don't trust the GitLab web editor).

**Comment by leif81** [comment]
I hear what you're saying Dan, it's possible. The one question in my mind is why when my coworkers and I turned off the extension the issue stopped happening. Coincidence, maybe. It is sometimes tricky to reproduce.

This doesn't cement anything, in the last 15 minutes I lost edits three times in a row. Each time was before my eyes and no pets or co-workers in the room! 

I'm feeling close to something that's reproducable. 🕵️

**Comment by leif81** [comment]
Ok, I think there's something to the above. Couple other bits of evidence.

- When the extension OFF, I can't reproduce the above at all.
- If the extension is ON, but toggled off from the "A" button in the Chrome bar, it still happens when it does the "A" becomes activated on it's own.

**Comment by mojavelinux** [comment]
Nice investigative work!

I'll try to reproduce on my end and report back.

**Comment by mojavelinux** [comment]
I'm able to confirm exactly the same behavior.

**Comment by Mogztter** [comment]
@leif81 Sorry for the 3 years delay 😅 

I did try to reproduce this issue with version 2.6.1 and Chrome 90.0.4430.93 but I can't. I guess it was fixed, probably when we released [version 2.5.0](https://github.com/asciidoctor/asciidoctor-browser-extension/releases/tag/v2.5.0) where we had to change a few things regarding how the extension is enabled.

**Comment by leif81** [comment]
😄 No problem.
I gave it a try again today and can't reproduce it anymore either (GitLab 13.12 and extension 2.6.1).

I'm good to close this!

**Comment by Mogztter** [comment]
Awesome, thanks for confirming that's it's now working 😃
