### ISSUE TITLE
Unable to render files opened via UNC path on MS Edge Dev

### ISSUE THREAD

**Issue by sysfu** [asciidoctor/asciidoctor-browser-extension#353]
I'm getting this error when opening files via UNC paths.

"DevTools failed to load SourceMap: Could not load content for chrome-extension://iaalpfgpbocpdfblpnhhgllgbdbchmia/js/vendor/chartist.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME"

Same file opening from local path works fine.

**Comment by Mogztter** [comment]
I think it's the same issue: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/320
But I don't think that's the reason why files are not rendered using UNC paths.

The error will not show up in the page console because we fetch the content from the background script. You should inspect the background page: https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/debugging-extensions#background-script-debugging

> Same file opening from local path works fine.

I don't think that's true, you should have the same error/warning in the console because this [source map file](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map) is not included (most of the time this file is only used in development when using a minified file).

**Comment by sysfu** [comment]
I'm running Edge _Dev_ Version 83.0.478.10 (Official build) dev (64-bit), the instructions provided appear to be for the previous EdgeHTML based version.

**Comment by Mogztter** [comment]
@sysfu if you go to `edge://extensions/?id=iaalpfgpbocpdfblpnhhgllgbdbchmia` (or right click on the extension icon and "Manage extensions") you should see:

![backgroundpage](https://user-images.githubusercontent.com/333276/79789809-0d786000-834b-11ea-9346-b35f68292fdf.png)

Enable "Developer mode" and click on "Background page (Inactive);". And here's what I get when I'm trying to open a file via UNC path:

![notallowed](https://user-images.githubusercontent.com/333276/79789803-0bae9c80-834b-11ea-9c15-39c3384ba05b.png)

I believe that this is more or less the same issue as described here https://github.com/asciidoctor/asciidoctor-browser-extension/issues/94. Unfortunately, I didn't find how to disable web security in Edge Dev...

**Comment by sysfu** [comment]
OK, here is the extension error log as obtained via the instructions above. 

[asciidoc-ext-error.log](https://github.com/asciidoctor/asciidoctor-browser-extension/files/4505841/asciidoc-ext-error.log)

**Comment by Mogztter** [comment]
I can confirm that this is the same issue.
The error `Not allowed to load local resource` is thrown by the browser while executing the `XMLHttpRequest` that fetches the content of the file.

For reference, here's a few resources:

- https://textslashplain.com/2019/10/09/navigating-to-file-urls/
- https://stackoverflow.com/questions/34901523/file-url-not-allowed-to-load-local-resource-in-the-internet-browser/35014520

So for now, I guess that the only workarounds are:
- Copy the files to your local disk
- Serve the files over HTTP (using an HTTP server)
- Somehow disable web security on Edge Dev

**Comment by sysfu** [comment]
Yeah, that's a bummer, I had moved all my ASCIIDOC formatted procedure files to a server share so they can be accessed anywhere. Not being able to render them in the browser with this extension might be a show stopper. I think the workaround will be to sync them locally using a tool like SyncThing.
