### ISSUE TITLE
is possible to inject/force :source-highlighter: highlightjs ?

### ISSUE THREAD

**Issue by apws** [asciidoctor/asciidoctor-browser-extension#423]
I found that if local .adoc file has not specified highlighter, then nothing is applied, once I place this at begining of file, its ok, so I wonder if its possible somehow to enforce this for .adoc even if it has specified other higlighter (replace all possible directives in includes too before ruby/opal code runs)? this CRX is end-to-end renderer with embedded highlightjs (possibly opening also from web not allowing changes to source), ya? ... anyway its not big deal for my usage now

**Comment by Mogztter** [comment]
> so I wonder if its possible somehow to enforce this for .adoc

If you don't want to add it in your document, you can add the `source-highlighter` attribute as a query parameter in the URL: `?source-highlighter=highlight.js` or you can add it in the options:

![options](https://user-images.githubusercontent.com/333276/94651110-38061600-02f8-11eb-9325-590384f768be.png)

> even if it has specified other higlighter 

Actually, the value of the attribute `source-highlighter` is ignored because the browser extension only supports Highlight.js. So if you declare `:source-highlighter: rouge` it will enable the syntax highlighting but it will use Highlight.js (not Rouge).

> replace all possible directives in includes too before ruby/opal code runs

I don't think we need to do that since the value of the `source-highlighter` attribute has no effect.

> this CRX is end-to-end renderer with embedded highlightjs (possibly opening also from web not allowing changes to source), ya? ... anyway its not big deal for my usage now

Sorry, I don't understand your question :thinking:

**Comment by apws** [comment]
Thanks, I completely missed the custom attributes field, sorry :-) Everything is clear, great product!

**Comment by Mogztter** [comment]
No worries, glad you find it useful 🤗
