### ISSUE TITLE
docs.asciidoctor.org/browser-extension shows Page not found, instead of docs.asciidoctor.org/browser-extension/latest/

### ISSUE THREAD

**Issue by sturtison** [asciidoctor/asciidoctor-browser-extension#655]
The [README.adoc](https://github.com/asciidoctor/asciidoctor-browser-extension/blob/3a27c4bd8663293e91fc6375e93f674ba4f303a3/README.adoc#L88C1-L88C1) directs the user to the user manual  https://docs.asciidoctor.org/browser-extension

**Expected behaviour:** Opens the latest page for the browser extension.

**Observed behaviour:** Displays page not found in content pane with the docs menu on the left.
NOTE: This is the same for all docs, eg https://docs.asciidoctor.org/asciidoc

**Solution:** Do we change the URL in README.adoc, or do something with the docs overall?

**Comment by mojavelinux** [comment]
If this is a versionless project from the user's perspective, what I recommend is setting the version to `~` to indicate that there is only a single version and that the version is not relevant. In this case, the version number will not be shown in the docs and the URL you cited will work.

If you want to retain the versioning, then the correct URL is https://docs.asciidoctor.org/browser-extension/latest/ (because a version must be specified).

**Comment by ggrossetie** [comment]
Fixed!
